# Generated by Django 5.2.8 on 2025-11-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('age_group', models.CharField(default='3-6 years', max_length=50)),
            ],
        ),
    ]
