# Generated by Django 5.2.8 on 2025-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_limited_edition_product_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age_group',
        ),
        migrations.AddField(
            model_name='product',
            name='size_range',
            field=models.CharField(default='6-12', max_length=50),
        ),
    ]
