# Generated by Django 5.2.7 on 2025-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_age_group_product_size_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Nike', max_length=100),
        ),
    ]
